version: '3'

services:

  endpoint:
    build:
        context: ./platform_in/
        dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5002 manage:app
    volumes:
      - ./platform_in/:/project/
    expose:
      - 5002
    env_file:
      - var.env
    environment:
      - FLASK_APP=app/__init__.py
      - FLASK_ENV=production
      - APP_SETTINGS=app.config.ProductionConfig

  nginx:
    build: ./nginx
    ports:
      - 1440:80
    depends_on:
      - endpoint
